# Tiền xử lý dữ liệu cho dữ liệu suy tim

In [4]:
import pandas as pd
df=pd.read_csv('Nhom 8_Data4AssociationRule.csv')
# Giảm chiều dữ liệu
df= df[['Diabetes','Family History','Smoking','Obesity','Alcohol Consumption',
        'Previous Heart Problems','Medication Use','Heart Attack Risk']]
# Chỉ chọn các trường hợp có khả năng bị suy tim để phân tích
df= df.loc[df['Heart Attack Risk']==1].reset_index(drop=True)
df

,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Previous Heart Problems,Medication Use,Heart Attack Risk
0,1,1,1,0,1,1,1,1
1,0,0,1,0,1,0,0,1
2,0,0,1,1,1,0,1,1
3,1,1,1,1,1,0,0,1
4,1,1,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...
3134,0,1,1,1,1,1,0,1
3135,1,1,1,0,1,1,1,1
3136,0,1,1,0,1,1,1,1
3137,0,1,1,1,1,1,0,1
3138,1,1,0,0,1,0,0,1

# Tìm tập phổ biến và luật kết hợp

In [6]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
# Tìm tập phổ biến khi min_sup = 0.5 bằng thuật toán apriori
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
# Tìm luật kết hợp từ các tập phổ biến đã lọc được ở trên với giá trị min_conf = 0.8
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)
# In ra các tập phổ biến
print("Frequent Itemsets:")
print(frequent_itemsets)
# In ra các luật tìm được
print("\nAssociation Rules:")
final_df = rules.loc[:, ['antecedents', 'consequents', 'confidence']]
print(final_df.to_string())

Frequent Itemsets:
     support                                           itemsets
0   0.663269                                         (Diabetes)
1   0.895190                                          (Smoking)
2   0.589041                              (Alcohol Consumption)
3   1.000000                                (Heart Attack Risk)
4   0.589997                                (Smoking, Diabetes)
5   0.663269                      (Heart Attack Risk, Diabetes)
6   0.531379                     (Alcohol Consumption, Smoking)
7   0.895190                       (Heart Attack Risk, Smoking)
8   0.589041           (Heart Attack Risk, Alcohol Consumption)
9   0.589997             (Heart Attack Risk, Smoking, Diabetes)
10  0.531379  (Heart Attack Risk, Alcohol Consumption, Smoking)

Association Rules:
                                 antecedents                   consequents  confidence
0                                 (Diabetes)                     (Smoking)    0.889529
1                                 (Diabetes)           (Heart Attack Risk)    1.000000
2                      (Alcohol Consumption)                     (Smoking)    0.902109
3                        (Heart Attack Risk)                     (Smoking)    0.895190
4                                  (Smoking)           (Heart Attack Risk)    1.000000
5                      (Alcohol Consumption)           (Heart Attack Risk)    1.000000
6              (Heart Attack Risk, Diabetes)                     (Smoking)    0.889529
7                        (Diabetes, Smoking)           (Heart Attack Risk)    1.000000
8                                 (Diabetes)  (Heart Attack Risk, Smoking)    0.889529
9   (Heart Attack Risk, Alcohol Consumption)                     (Smoking)    0.902109
10            (Alcohol Consumption, Smoking)           (Heart Attack Risk)    1.000000
11                     (Alcohol Consumption)  (Heart Attack Risk, Smoking)    0.902109

C:\Users\KIEU DOAN\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(